### ISSUE TITLE
Need help on setting up

### ISSUE THREAD

**Issue by dimassrio** [mlisook/paper-map-info#13]
Seems like i cant trigger the paper-map-info to open, upon closer look, i try to debug the process and find out that this.map of paper-map-info is always returned undefined. Any idea for the reason?

    <google-map id="gmap" api-key="xxx" latitude="0.9230613" longitude="118.2115722" zoom="5" disable-street-view-control language="id" map-type="terrain" additional-map-options='{"mapTypeControl":"true", "mapTypeControlOptions" : {"position": 9, "style":2}, "zoomControl":"true", "zoomControlOptions" : {"position": 8}}' click-events="true" mouse-events="true" single-info-window="true">
        <paper-map-info id="infoMarker" fade-in>test</paper-map-info>
    </google-map>

**Comment by mlisook** [comment]
Do you have more code you can share?  I'd like to have a look at what you are using to trigger the open, for example.

You may also want to have a look at the [demo page](https://mlisook.github.io/paper-map-info/).

In any case, I'm happy to help with whatever your specific use of the control is.

**Comment by dimassrio** [comment]
Thank you very much for your reply and time,

Here's what i use to trigger the open method

    listen : [
        'google-map-marker-click' : 'markerClick',
    ]

    markerClick : function(e){
        this.$.infoMarker.showInfoWindow(e.path[0].marker); //e.path[0] returning the google-map-marker
    },

is there any chance the event must be originated within the google-map?

    Event
        bubbles:true
        cancelBubble:false
        cancelable:false
        composed:false
        currentTarget:null
        defaultPrevented:false
        detail:_.wk
        eventPhase:0
        isTrusted:false
        path:Array[30]
        returnValue:true
        srcElement:my-app
        target:my-app
        timeStamp:6917.14
        type:"google-map-marker-click"
        __proto__:Event

the marker itself is added dynamically like this
    
    for(let j in markers){
        this.$.gmap.appendChild(markers[j]);
    }

interestingly enough when i try to debug the paper-map-info.js, specifically at showInfoWindows

    paperMapInfo.prototype.showInfoWindow = function (marker) {
        console.log(this.map); //return undefined
        var _this = this;
        if (this.map && marker) {
        // I can't never go here, because this.map returning undefined.
            if (this.isShowing) {
                this.close();
            }

**Comment by dimassrio** [comment]
Hmm i found another discovery, 

    <google-map id="gmap" api-key="xx" latitude="0.9230613" longitude="118.2115722" zoom="5" disable-street-view-control language="id" map-type="terrain" additional-map-options='{"mapTypeControl":"true", "mapTypeControlOptions" : {"position": 9, "style":2}, "zoomControl":"true", "zoomControlOptions" : {"position": 8}}' click-events="true" mouse-events="true" single-info-window="true">
       <google-map-marker latitude="0.9230613" longitude="118.2115722" click-events="true" on-google-map-marker-click="markerClick" icon="http://localhost:8080/images/pamtas-normal@0.5x.png"></google-map-marker>
    </google-map>

When i try to trigger the function declaratively, the paper-map-info open, although its not perfect. And im checking the paper-map-info.map is returning the map object.

![screen shot 2016-12-28 at 9 36 16 am](https://cloud.githubusercontent.com/assets/803565/21512545/43645918-cce1-11e6-96f9-0e1cee82ff93.png)

However, if i trigger the function programatically via listen method.

    this.listen(x, 'google-map-marker-click', 'markerClick');

The function markerClick is running, but no effect on paper-map-info. (when i check, paper-map-info.map is returning undefined)

**Comment by mlisook** [comment]
From what I can see after a little testing it is not  the listener - must have something to do with the way you are adding the markers.  I'll try to mock up adding markers to the DOM in the way you mentioned earlier, but wanted to eliminate the listener as a potential issue since it looked fine to me.

The contents of the `paper-map-info` should also be wrapped in an element (see code below).

In the sample below I used the listeners declaration and `markerClick `handler you showed earlier in the thread and it worked fine. Note that I don't have the handler named on the `google-map-marker`:
```

<link rel="import" href="../../bower_components/google-map/google-map.html" />
<link rel="import" href="../../bower_components/paper-map-info/paper-map-info.html" />
<link rel="import" href="../../bower_components/iron-icons/iron-icons.html" />
  <dom-module id="i13-test">
    <template>
      <style>
        :host {
          display: inline-block;
        }
        google-map {
          height: 400px;
          width: 400px;
        }
      </style>
      <google-map id="gmap" api-key="xxx" latitude="-6.23" longitude="106.82" zoom="5" disable-street-view-control language="id" map-type="terrain" additional-map-options='{"mapTypeControl":"true", "mapTypeControlOptions" : {"position": 9, "style":2}, "zoomControl":"true", "zoomControlOptions" : {"position": 8}}' click-events="true" mouse-events="true" single-info-window="true">
        <template is="dom-repeat" items="[[locations]]" as="l">
          <google-map-marker click-events latitude="[[l.latLng.lat]]" longitude="[[l.latLng.lng]]" >
          </google-map-marker>
        </template>

        <paper-map-info id="infoMarker" fade-in>
          <div>
            test
          </div>
        </paper-map-info>
      </google-map>


    </template>
    <script>
    Polymer({

      is: 'i13-test',

      properties: {
        locations: {
          type: Array,
          notify: true
        }
      },
      listeners : {
          'google-map-marker-click' : 'markerClick',
      },

      /**
       * Initialize demo data
       */
      ready: function() {
        this.locations = [{
          location: "Capital Place",
          latLng: {
            lat: -6.232340,
            lng: 106.820322
          }
        }, {
          location: "RS Handayani",
          latLng: {
            lat: -4.839877,
            lng: 104.885069
          }
        }, {
          location: "Museum Sultan Mahmud Badaruddin",
          latLng: {
            lat: -2.990252,
            lng: 104.761133
          }
        }];
      },

      markerClick : function(e){
          this.$.infoMarker.showInfoWindow(e.path[0].marker); //e.path[0] returning the google-map-marker
      }

    });
    </script>
  </dom-module>

```
![i13-1](https://cloud.githubusercontent.com/assets/1044471/21513555/e1575a08-cc6e-11e6-85d9-6a77f93d62d2.png)

**Comment by dimassrio** [comment]
Yes, looks like thats the case, im experimenting with dom-repeat too, and can successfully open the paper-map-info. Looks like its because polymer can't data-bind programatically, so it could be the reason paper-map-info cannot getting the map instances.

One simple question though, is there any way to disable the pan when marker clicked? Since it react quite weird when i click the marker for the first time o.O.

Thanks a lot for your help @mlisook and enjoy your holiday!

I think its safe to close this issue :),

**Comment by mlisook** [comment]
I removed the data bound google-map-marker tag and dom-repeat template, and added markers in a for loop
```
    for (let j in this.locations) {
          this.locations[j].marker = document.createElement('google-map-marker');
          this.locations[j].marker.latitude = this.locations[j].latLng.lat;
          this.locations[j].marker.longitude = this.locations[j].latLng.lng;
          this.locations[j].marker.clickEvents = true;
          Polymer.dom(this.$.gmap).appendChild(this.locations[j].marker);
        }
```
This worked fine for me.

The map will pan if the info window does not fit within the viewable frame of the map that is showing when you click.  It should only pan just enough to get the whole info window in frame.  To do that it checks the position of the marker, the size (well the height) of the marker, and size of the infowindow.  The map shouldn't pan unless it needs to to show the window touching the marker.

Revised sample code below:
```
<link rel="import" href="../../bower_components/google-map/google-map.html" />
<link rel="import" href="../../bower_components/paper-map-info/paper-map-info.html" />
<link rel="import" href="../../bower_components/iron-icons/iron-icons.html" />
  <dom-module id="i13-test">
    <template>
      <style>
        :host {
          display: inline-block;
        }
        google-map {
          height: 400px;
          width: 400px;
        }
      </style>
      <google-map id="gmap" api-key="xxx" latitude="-6.23" longitude="106.82" zoom="5" disable-street-view-control language="id" map-type="terrain" additional-map-options='{"mapTypeControl":"true", "mapTypeControlOptions" : {"position": 9, "style":2}, "zoomControl":"true", "zoomControlOptions" : {"position": 8}}' click-events="true" mouse-events="true" single-info-window="true">
        <paper-map-info id="infoMarker" fade-in>
          <div>
            test
          </div>
        </paper-map-info>
      </google-map>


    </template>
    <script>
    Polymer({

      is: 'i13-test',

      properties: {
        locations: {
          type: Array,
          notify: true
        }
      },
      listeners : {
          'google-map-marker-click' : 'markerClick',
      },

      /**
       * Initialize demo data
       */
      ready: function() {
        this.locations = [{
          location: "Capital Place",
          latLng: {
            lat: -6.232340,
            lng: 106.820322
          }
        }, {
          location: "RS Handayani",
          latLng: {
            lat: -4.839877,
            lng: 104.885069
          }
        }, {
          location: "Museum Sultan Mahmud Badaruddin",
          latLng: {
            lat: -2.990252,
            lng: 104.761133
          }
        }];

        for (let j in this.locations) {
          this.locations[j].marker = document.createElement('google-map-marker');
          this.locations[j].marker.latitude = this.locations[j].latLng.lat;
          this.locations[j].marker.longitude = this.locations[j].latLng.lng;
          this.locations[j].marker.clickEvents = true;
          Polymer.dom(this.$.gmap).appendChild(this.locations[j].marker);
        }

      },

      markerClick : function(e){
          this.$.infoMarker.showInfoWindow(e.path[0].marker); //e.path[0] returning the google-map-marker
      }

    });
    </script>
  </dom-module>

```

**Comment by mlisook** [comment]
If you are using a custom icon be sure to set the `anchor.x` and `anchor.y` properties - `anchor: new google.maps.Point(anchor.x, anchor.y)`

**Comment by dimassrio** [comment]
```
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/polymer-ts/polymer-ts.html">
<link rel="import" href="../bower_components/google-map/google-map.html">
<link rel="import" href="../bower_components/google-map/google-map-marker.html">
<link rel="import" href="../bower_components/paper-map-info/paper-map-info.html">

<dom-module id="smdp-map3">
  <template>
    <style include="shared-styles">
	    :host {
	      display: block;
	      min-height: 100vh;
	      background: #FFF;
	    }
		#gmap{
			height: 100vh;
		}
		#infoWindow{
			--paper-map-info-mixin : {
				background-color: darkgray;
			};
			--paper-map-info-beak-mixin : {
				fill: blue;
		    	stroke: blue;
		   }
		}
    </style>
	<google-map id="gmap" api-key="xx" latitude="0.9230613" longitude="118.2115722" zoom={{zoom}} disable-street-view-control language="id" map-type="terrain" additional-map-options='{"mapTypeControl":"true", "mapTypeControlOptions" : {"position": 9, "style":2}, "zoomControl":"true", "zoomControlOptions" : {"position": 8}}' click-events="true" mouse-events="true" single-info-window="true" markers=[[markers]] fit-to-markers>
		<template is="dom-repeat" items="{{markers}}">
			<google-map-marker latitude="{{item.latitude}}" longitude="{{item.longitude}}" click-events on-google-map-marker-click="_markerClick"></google-map-marker>
		</template>
		<google-map-marker latitude="0.9230613" longitude="118.2115722" click-events on-google-map-marker-click="_markerClick"></google-map-marker>
		<paper-map-info id="infoWindow">
			<div class="layout horizontal">test</div>
		</paper-map-info>
	</google-map>
  </template>
  <script>
    Polymer({
      is : 'smdp-map3',
	  _markerClick : function(e){
		  this.$.infoWindow.showInfoWindow(e.path[0].marker);
	  }
    });
  </script>
</dom-module>
```

This is bare minimum of my project right now,

Before marker click : 
![screen shot 2016-12-28 at 2 16 26 pm](https://cloud.githubusercontent.com/assets/803565/21516165/64260c88-cd08-11e6-9913-500fb0f423ed.png)

After marker click, its suddenly panned to the top left
![screen shot 2016-12-28 at 2 16 36 pm](https://cloud.githubusercontent.com/assets/803565/21516196/978693a4-cd08-11e6-8d41-39ce059299b0.png)

This is also happening with your sample code, yet i dont know what could be the trigger...

**Comment by mlisook** [comment]
I am continuing to look into this but I'm not getting that effect when running your code sample:

![t1](https://cloud.githubusercontent.com/assets/1044471/21523638/cb95de1e-ccc4-11e6-8cc8-75ccafbdcf46.gif)

**Comment by mlisook** [comment]
Are there any console messages?

**Comment by dimassrio** [comment]
![paper-map-info-weird-behaviour_clipchamp_480p](https://cloud.githubusercontent.com/assets/803565/21527054/1ee48192-cd5b-11e6-83a2-a6809cad21c8.gif)

Nope, nothing on the console. FYI im using it as a page from PSK shell apps. Doubt it have any effect.

**Comment by dimassrio** [comment]
> If you are using a custom icon be sure to set the anchor.x and anchor.y properties - anchor: new google.maps.Point(anchor.x, anchor.y)

Umm just got stumbled on this after changing icon ^^, which anchor i need to change? and the x and y is referenced to the latitude and longitude right?

**Comment by mlisook** [comment]
Well your last GIF seems to be using the default/built in marker, but if you do want to use a custom image or SVG vector as a marker you would bind to the `icon `property of `google-map-marker` (or set it in code) to an object:

```
<google-map-marker ... icon="[[item.marker.icon]]" ...

// say your marker image, foo.png, is 30px wide by 40px high 
this.markerPoints[i].marker.icon = { anchor: new google.maps.Point(15, 40), url: "/images/foo.png";
```
But as I said, from your GIF it looks like a standard marker.

**Comment by mlisook** [comment]
I have not been able to cause this behaviour.  I doubt it is related to the PSK since I've got a couple of projects running in production with paper-drawer-panel.

I'd appreciate it if you could gather a little data for me in debug, if you have the time.  

In `paper-map-info.ts`, line 356, set a breakpoint and print out the following values (expand all properties):

- this._marker.getPosition()
- this._dim
- point
- ptop
- pleft

Also, are you setting the contents of the infowindow before or after calling `showInfoWindow`?  (This probably doesn't matter since I've tried it both ways).

As you can tell, I really don't know what is going on yet, but definitely want to figure it out.

**Comment by dimassrio** [comment]
Sure! here's the required information

`this._marker.getPosition();`
![screen shot 2016-12-29 at 11 54 04 am](https://cloud.githubusercontent.com/assets/803565/21537022/8d9f0550-cdbd-11e6-88da-e37d9c86aa75.png)

`this._dim`
![screen shot 2016-12-29 at 11 55 54 am](https://cloud.githubusercontent.com/assets/803565/21537033/ca1a915c-cdbd-11e6-8638-9f91b5e838ca.png)

`point`
![screen shot 2016-12-29 at 11 56 38 am](https://cloud.githubusercontent.com/assets/803565/21537042/f0df2cc6-cdbd-11e6-8bba-206abb20b57f.png)

`ptop : 111`

`pleft : 146`

**Comment by mlisook** [comment]
Thank you.  The debug data above showing `this._dim.map` at 100 x 100 has helped me identify the reason for this error leading to panning the map to the top left.

In `paper-map-info.showInfoWindow(marker)` the listeners are initialized twice - `this._initListeners()` at 374 and again at 394.  At 374 this is happening before `this.isShowing = true` and `this.$.infocarddiv.style.display = "block"`.  When the second statement executes `resize-aware` detects a size change to the info window and fires an event which triggers `_contentChanged()` and leads to map panning because the size of the map has not yet been set (`showInfoWindow` at 396)

On my laptop the error is hit or miss happening 20% of the time under shadow DOM and 5-10% under shady DOM so it's been difficult to diagnose.

I'll make a patch and let you know when I've pushed it to Github.

**Comment by mlisook** [comment]
I've merged in a fix for the map panning issue.  

You can do a bower update to get the changes.

Thanks again.

**Comment by mlisook** [comment]
Closing this issue as resolved.
