### ISSUE TITLE
Trying to use your element but getting "polymer is not defined" error 

### ISSUE THREAD

**Issue by lbustelo** [mlisook/paper-map-info#2]
![screen shot 2016-06-20 at 5 00 48 pm](https://cloud.githubusercontent.com/assets/2474841/16211675/9be45a58-3708-11e6-9371-331bc558c6b9.png)

**Comment by mlisook** [comment]
I apologize, I thought I had put the referencing instructions in the readme.md, but see they are only in index.html - I'll update the readme.

The element was written in typescript and requires a reference to polymer-ts in the head:

```
<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
<link rel-"import" href="bower_components/polymer/polymer.html" />
<link rel-"import" href="bower_components/polymer-ts/polymer-ts.html" />
<link rel-"import" href="bower_components/paper-map-info/paper-map-info.html" />
```

Of course using your path to bower_components.

You can see an example in demo/index.html

**Comment by mlisook** [comment]
Thank you for identifying this issue.  I've updated the README.md.

**Comment by lbustelo** [comment]
I don't think that documenting this is enough. To my understanding, it is encouraged that each element is self contained. So if your element requires polymer or even polymer-ts, then your component should link to it. Notice how all the paper-\* element actually link to polymer itself. I see that you are doing that [here](https://github.com/mlisook/paper-map-info/blob/master/paper-map-info.html#L44), so why would I need to add that to the script included in my app.

Feels like you are bleeding out implementation details.

**Comment by lbustelo** [comment]
BTW... I did not need to add those script tags to use your tag. It just starting working... I will open other issues as I find them.

![info_panel_working](https://cloud.githubusercontent.com/assets/2474841/16242239/2b4beaa4-37b7-11e6-8bf5-576f9662287c.gif)
