### ISSUE TITLE
missing requirement of 'paper-material' in bower.json

### ISSUE THREAD

**Issue by lbustelo** [mlisook/paper-map-info#3]
![screen shot 2016-06-20 at 5 06 00 pm](https://cloud.githubusercontent.com/assets/2474841/16211791/5a2ef7b6-3709-11e6-9bc2-4e22c6ef551f.png)

**Comment by mlisook** [comment]
Thank you.  I'll push a fix for this right away.

**Comment by mlisook** [comment]
Thank you for identifying this issue.  I've updated added the dependency to bower.json.

**Comment by lbustelo** [comment]
@mlisook you can close this... I can confirm that your changes worked.
